### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by thejun2** [newrelic/nri-perfmon#1]
also, can this be added to new relic's storagesample, or can i create a new group sample name??  

 {
	  "counterlist": [
    {
     "query": "select FreeAndZeroPageListBytes from Win32_PerfFormattedData_PerfOS_Memory",
     "eventname": "system.memory.freepage"
    },
    {
      "query": "select FreeSpace from Win32_Volume",
      "eventname": "wmi.disk.freespacebytes"
    },
    {
      "query": "select Capacity from Win32_Volume",
      "eventname": "wmi.disk.capacitybytes"
    },
	{
      "query": "select AvgDiskSecPerRead from Win32_PerfRawData_PerfDisk_PhysicalDisk",
      "eventname": "system.io.latency.read"
    },
	{
      "query": "select AvgDiskSecPerWrite from Win32_PerfRawData_PerfDisk_PhysicalDisk",
      "eventname": "system.io.latency.write"
    },
	{
      "query": "select AvgDiskSecPerTransfer from Win32_PerfRawData_PerfDisk_PhysicalDisk",
      "eventname": "system.io.latency.transfer"
    },
	{
      "query": "select AvgDiskQueueLength from Win32_PerfRawData_PerfDisk_PhysicalDisk",
      "eventname": "system.io.latency.diskqueuelength"
    }
		
	]
}

**Comment by sschwartzman** [comment]
I don't believe this can add to "storagesample" and have it appear in the same form as the rest of the data there. You'd be best off to keep this data in custom events.

Can I suggest consolidating some of this too? Like so - bear in mind you can leave out the `"counters"` stanzas if you are OK with the default names of the attributes, i.e. `AvgDiskQueueLength` instead of `system.io.latency.diskqueuelength`.

```json
{
	"counterlist": [{
			"query": "select FreeAndZeroPageListBytes from Win32_PerfFormattedData_PerfOS_Memory",
			"eventname": "Perfmon_Memory",
			"counters": [{
				"attrname": "system.memory.freepage",
				"counter": "FreeAndZeroPageListBytes"
			}]
		},
		{
			"query": "select Capacity, FreeSpace, from Win32_Volume",
			"eventname": "Perfmon_Volume",
			"counters": [{
				"attrname": "wmi.disk.freespacebytes",
				"counter": "FreeSpace"
			}, {
				"attrname": "wmi.disk.capacitybytes",
				"counter": "Capacity"
			}]
		},
		{
			"query": "select AvgDiskSecPerRead, AvgDiskSecPerWrite, AvgDiskSecPerTransfer, AvgDiskQueueLength from Win32_PerfRawData_PerfDisk_PhysicalDisk",
			"eventname": "Perfmon_PhysicalDisk",
			"counters": [{
				"attrname": "system.io.latency.read",
				"counter": "AvgDiskSecPerRead"
			}, {
				"attrname": "system.io.latency.write",
				"counter": "AvgDiskSecPerWrite"
			}, {
				"attrname": "system.io.latency.transfer",
				"counter": "AvgDiskSecPerTransfer"
			}, {
				"attrname": "system.io.latency.diskqueuelength",
				"counter": "AvgDiskQueueLength"
			}]
		}
	]
}
```
