### ISSUE TITLE
error="no content to parse

### ISSUE THREAD

**Issue by JorgeAlaniz007** [newrelic/nri-perfmon#11]
Hi S,
Deployed the integration as is, Im able to see some events in Insights but not all of them
> NETCLRExceptions
> NETCLRInterop
> NETCLRJit
> NETCLRLoading
> NETCLRLocksAndThreads
> NETCLRMemory

In logs I see below error:
time="2019-10-16T14:52:15-07:00" level=warning msg="cannot handle integration output" error="no content to parse" instance=nri-perfmon-metrics integration=com.newrelic.perfmon prefix=integration/nri-perfmon working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations"
time="2019-10-16T14:52:15-07:00" level=warning msg="cannot handle integration output" error="**invalid character 'c'** looking for beginning of value" instance=nri-perfmon-metrics integration=com.newrelic.perfmon prefix=integration/nri-perfmon working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations"
time="2019-10-16T14:52:15-07:00" level=warning msg="cannot handle integration output" error="**invalid character 'i**' looking for beginning of value" instance=nri-perfmon-metrics integration=com.newrelic.perfmon prefix=integration/nri-perfmon working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations"
time="2019-10-16T14:52:15-07:00" level=warning msg="cannot handle integration output" error="**invalid character ':'** in literal null (expecting 'u')" instance=nri-perfmon-metrics integration=com.newrelic.perfmon prefix=integration/nri-perfmon working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations"
time="2019-10-16T14:52:15-07:00" level=warning msg="cannot handle integration output" error="invalid character 'v' looking for beginning of value" instance=nri-perfmon-metrics integration=com.newrelic.perfmon prefix=integration/nri-perfmon working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations"
time="2019-10-16T14:52:15-07:00" level=warning msg="cannot handle integration output" error="no content to parse" instance=nri-perfmon-metrics integration=com.newrelic.perfmon prefix=integration/nri-perfmon working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations"
time="2019-10-16T14:52:15-07:00" level=error msg="Integration command failed" error="exit status 1" instance=nri-perfmon-metrics integration=com.newrelic.perfmon prefix=integration/nri-perfmon stderr= working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations"

seems like its looking for the configurations but not able to parse them all? I only updated verbose in yml file

name: com.newrelic.perfmon
description: Perfmon On-Host Integration
protocol_version: 1
os: windows
commands:
  metrics:
    command:
    - .\nri-perfmon\nri-perfmon.exe
    - -v 1
    prefix: integration/nri-perfmon
    interval: 15

Any ideas?

Thanks!

**Comment by sschwartzman** [comment]
Can you attach all of your config files (config.json and the yml file) to this ticket to review?

**Comment by JorgeAlaniz007** [comment]
[custom-integrations.zip](https://github.com/newrelic/nri-perfmon/files/3740481/custom-integrations.zip)

**Comment by sschwartzman** [comment]
So in your definition.yml file, you need 2 more spaces before each of the lines that have dashes to start. YAML is very finicky in this way. Here is a fixed version:

```
#
# New Relic Infrastructure Perfmon Integration
#
name: com.newrelic.perfmon
description: Perfmon On-Host Integration
protocol_version: 1
os: windows
commands:
  metrics:
    command:
      - .\nri-perfmon\nri-perfmon.exe
      - -v 1
    prefix: integration/nri-perfmon
    interval: 15
```

**Comment by sschwartzman** [comment]
Any update @JorgeAlaniz007 ?

**Comment by JorgeAlaniz007** [comment]
Hi Seth,
Tested on my personal and I'm having the same issue, will try today in another win server
Thanks!

**Comment by sschwartzman** [comment]
Did you test with the version I put in above with the proper spacing? (Tabs are not acceptable, must be spaces, and be the exact amount!)
If so, can you paste you config file into yamllint and verify it's valid yaml? http://www.yamllint.com/

**Comment by JorgeAlaniz007** [comment]
Hi Seth,
Yes, we are using the provided config file and validated it in yamlint
We are facing the same error, I'm attaching the complete log
Thanks!
[newrelig-infra.log](https://github.com/newrelic/nri-perfmon/files/3769035/newrelig-infra.log)

**Comment by sschwartzman** [comment]
Let's see what the integration binary is coming back with - it may be that there's no data for some of the counters, which is OK. It could also be a parsing issue if the data is coming back with some weird format.

Please run the following at command line and paste the output here:
```
cd \Program Files\New Relic\newrelic-infra\custom-integrations
nri-perfmon\nri-perfmon.exe 
```

**Comment by JorgeAlaniz007** [comment]
This is from my laptop

[Perfmon-output.txt](https://github.com/newrelic/nri-perfmon/files/3769362/Perfmon-output.txt)

**Comment by JorgeAlaniz007** [comment]
Hi Seth,
Got it, yes, lets close this
Thanks for your support :)
