### ISSUE TITLE
Seeing the following nri-perfmon errors in Windows Event Logs in Production! Please see attachment.

### ISSUE THREAD

**Issue by mravikum2020** [newrelic/nri-perfmon#14]
Log Name:      Application
Source:        nri-perfmon
Date:          5/7/2020 7:58:47 AM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      COACMPWEBUAT51.brighthorizons.com
Description:
Exception occurred in polling. Invalid class : Select Name, NumberofExcepsThrown, NumberofExcepsThrownPersec, NumberofFiltersPersec, NumberofFinallysPersec, ThrowToCatchDepthPersec from Win32_PerfFormattedData_NETFramework_NETCLRExceptions
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="nri-perfmon" />
    <EventID Qualifiers="0">0</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-05-07T13:58:47.000000000Z" />
    <EventRecordID>1583144</EventRecordID>
    <Channel>Application</Channel>
    <Computer>COACMPWEBUAT51.brighthorizons.com</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Exception occurred in polling. Invalid class : Select Name, NumberofExcepsThrown, NumberofExcepsThrownPersec, NumberofFiltersPersec, NumberofFinallysPersec, ThrowToCatchDepthPersec from Win32_PerfFormattedData_NETFramework_NETCLRExceptions</Data>
  </EventData>
</Event>

**Comment by mravikum2020** [comment]
[nri-perfmon errors.zip](https://github.com/newrelic/nri-perfmon/files/4593558/nri-perfmon.errors.zip)

**Comment by sschwartzman** [comment]
can you please run the following commands?

1. In Powershell (as Administrator):
```
get-ciminstance Win32_PerfFormattedData_NETFramework_NETCLRExceptions` >> ~\Desktop\nri-perfmon.get-ciminstance.log
```

2. In Command Prompt (as Administrator): 
```
cd "c:\Program Files\New Relic\newrelic-infra\custom-integrations"
nri-perfmon\nri-perfmon.exe -v > ~\Desktop\nri-perfmon.verbose.log
```
Let the 2nd command run for 10 seconds or so and then stop the process.
Then, please post both of those logs to this ticket.

**Comment by sschwartzman** [comment]
By the way, these "invalid class" errors are nothing wrong in the Perfmon OHI. This simply means that the class defined in the config file does not have data. You should also see "WARN" messages after those that show those queries being removed from being re-run. 

I did also notice this error in what you sent me, which points to your issue - that perf counters on that box are somehow not reporting properly:

```

**Comment by mravikum2020** [comment]
Powershell output.

PS C:\Windows\system32> Get-CimInstance

cmdlet Get-CimInstance at command pipeline position 1
Supply values for the following parameters:
ClassName: Win32_PerfFormattedData_NETFramework_NETCLRExceptions
Get-CimInstance : Invalid class
At line:1 char:1
+ Get-CimInstance
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (root\cimv2:Win3...ETCLRExceptions:String) [Get-CimInstance], CimExceptio
   n
    + FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand

**Comment by mravikum2020** [comment]
[nri-perfmon.verbose.zip](https://github.com/newrelic/nri-perfmon/files/4611840/nri-perfmon.verbose.zip)

**Comment by sschwartzman** [comment]
As with the other ticket you submitted, "true" needs to be added to the verbose command, like so:
```
cd "c:\Program Files\New Relic\newrelic-infra\custom-integrations"
nri-perfmon\nri-perfmon.exe -v > ~\Desktop\nri-perfmon.verbose.log
```

Bear in mind that I am pretty confident the issue is NOT in the OHI but rather in the Perfmon counters in your Windows host, which will require your efforts to rebuild those counters (not something we can offer).

**Comment by mravikum2020** [comment]
Sounds good Seth, could we also modify the config.json to remove counters which are not setup on our PRD Servers.
Therefore, we could bypass the error messages we see in Windows event logs.


Thanks,
Manoj

**Comment by sschwartzman** [comment]
Yes, you are welcome to edit your config file.
