### ISSUE TITLE
Seeing the following nri-perfmon errors in Windows event logs!! Please assist.

### ISSUE THREAD

**Issue by mravikum2020** [newrelic/nri-perfmon#15]
Log Name:      Application
Source:        nri-perfmon
Date:          5/11/2020 9:20:44 AM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      COACMPAPPUAT01.brighthorizons.com
Description:
Exception occurred in processing next value. Instance '_LM_W3SVC_6_ROOT' does not exist in the specified Category.
   at System.Diagnostics.CounterDefinitionSample.GetInstanceValue(String instanceName)
   at System.Diagnostics.PerformanceCounter.NextSample()
   at System.Diagnostics.PerformanceCounter.NextValue()
   at NewRelic.PerfmonPlugin.PollPerfCounters() in Z:\eclipse\nri-perfmon\nri-perfmon\Plugin.cs:line 452
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="nri-perfmon" />
    <EventID Qualifiers="0">0</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-05-11T15:20:44.000000000Z" />
    <EventRecordID>18397552</EventRecordID>
    <Channel>Application</Channel>
    <Computer>COACMPAPPUAT01.brighthorizons.com</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Exception occurred in processing next value. Instance '_LM_W3SVC_6_ROOT' does not exist in the specified Category.
   at System.Diagnostics.CounterDefinitionSample.GetInstanceValue(String instanceName)
   at System.Diagnostics.PerformanceCounter.NextSample()
   at System.Diagnostics.PerformanceCounter.NextValue()
   at NewRelic.PerfmonPlugin.PollPerfCounters() in Z:\eclipse\nri-perfmon\nri-perfmon\Plugin.cs:line 452</Data>
  </EventData>
</Event>

**Comment by mravikum2020** [comment]
[nri-perfmon-errors.zip](https://github.com/newrelic/nri-perfmon/files/4610517/nri-perfmon-errors.zip)

**Comment by mravikum2020** [comment]
Please see the attached Windows Events bundle.

**Comment by sschwartzman** [comment]
Can you please run the following command in Command Prompt (as Administrator):
cd "c:\Program Files\New Relic\newrelic-infra\custom-integrations"
nri-perfmon\nri-perfmon.exe -v > ~\Desktop\nri-perfmon.verbose.log
Let the command run for 10 seconds or so and then stop the process.
Then, please post the log to this ticket.

**Comment by mravikum2020** [comment]
Sure Seth, please see attachment.

**Comment by mravikum2020** [comment]
[nri-perfmon.verbose.zip](https://github.com/newrelic/nri-perfmon/files/4611718/nri-perfmon.verbose.zip)

**Comment by sschwartzman** [comment]
Oops, verbose didn't run, I forgot "true" in the command. Please re-run like so:

```
cd "c:\Program Files\New Relic\newrelic-infra\custom-integrations"
nri-perfmon\nri-perfmon.exe -v true > ~\Desktop\nri-perfmon.verbose.log
```
