### ISSUE TITLE
INSTALL

### ISSUE THREAD

**Issue by diego-miranda-inter** [newrelic/nri-perfmon#16]
When trying to install the error code always appears below:

    :MyInvocation.MyCommand.Path
Split-Path : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:26
+ $script_dir = Split-Path $script:MyInvocation.MyCommand.Path
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCo
   mmand

can you help us with this installation?

![image](https://user-images.githubusercontent.com/65189239/81598361-8ba1b280-939d-11ea-90be-a48c0790832e.png)

**Comment by sschwartzman** [comment]
I think the issue is that you cloned the repo instead of downloading the release. Please try that instead: https://github.com/newrelic/nri-perfmon/releases/tag/0.5.1
