### ISSUE TITLE
ASP.NET counter from PerfMon provider isn't reported

### ISSUE THREAD

**Issue by brunotag** [newrelic/nri-perfmon#18]
We noticed the "ASP.NET" counter from the PerfMon provider isn't reported.

Example config:

```
{
  "counterlist": [
       {
      "provider": "PerfCounter",
      "category": "ASP.NET",
	  "instance": "*",
      "counters": [
        { "counter": "*" }
      ]
    }
  ]
}
```

We think this happens because the ASP.NET counter legitimately doesn't have `instances`, but currently [the code doesn't allow for that](https://github.com/newrelic/nri-perfmon/blob/master/nri-perfmon/Plugin.cs#L52).

That could be easily fixed with a little code change (we've tested this on our environment, Windows Server 2012 R2 64bit).

See: https://github.com/newrelic/nri-perfmon/pull/17

**Comment by sschwartzman** [comment]
Merged! Thanks @brunotag!

New release with your PR included: https://github.com/newrelic/nri-perfmon/releases/tag/0.5.1
