### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by johnbowker** [newrelic/nri-perfmon#2]
I tried to compile the solution but MSBuild is complaining about files missing from the solution:

`Resources.rex` `AssemblyInfo.cs` etc.

Did these get missed in a `git add`?

**Comment by sschwartzman** [comment]
@johnbowker I fixed the .gitignore to allow the files in /Properties, so they should be there now.

Out of curiosity, what do you need to build the solution for? Is there something in the release that's missing?
