### ISSUE TITLE
Eventlog messages all have EventId zero

### ISSUE THREAD

**Issue by rpresser** [newrelic/nri-perfmon#27]
Example:

```
Warning	12/2/2020 3:11:52 PM	nri-perfmon	0	None
Error	12/2/2020 3:11:52 PM	nri-perfmon	0	None
Warning	12/2/2020 3:11:52 PM	nri-perfmon	0	None
Error	12/2/2020 3:11:52 PM	nri-perfmon	0	None
```

Assigning some event IDs could be helpful

**Comment by sschwartzman** [comment]
What should the eventId correspond to?

**Comment by rpresser** [comment]
It's [application-specific](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.eventlog.writeentry?redirectedfrom=MSDN&view=dotnet-plat-ext-5.0#System_Diagnostics_EventLog_WriteEntry_System_String_System_String_System_Diagnostics_EventLogEntryType_System_Int32_), so I guess the way to start is to collect some typical messages and see if they fall into common categories, then assign numbers there.

**Comment by sschwartzman** [comment]
Ah, I see. I'd say if you have any suggestions then we can work them in (or you can PR back to the repo to do this) but otherwise I'm going to leave this one be. The message text is the useful part, categorically there aren't many different types of errors experienced by this plugin.
