### ISSUE TITLE
Insights not receiving metrics

### ISSUE THREAD

**Issue by KWLynch** [newrelic/nri-perfmon#3]
I have installed the plugin using the manual method as described. Metrics are printed to stdout when executing nri-perfmon.exe. However, Insights is not getting the metrics. I see the error below in the agent-infra log after each poll:
time="2019-06-17T15:02:35-04:00" level=error msg="executing data source" data prefix=integration/nri-perfmon error="exit status 2148734720" plugin name=nri-perfmon-metrics stderr=
Any ideas on what the issue may be?

**Comment by sschwartzman** [comment]
Can you post your config files here?

- [ ] `C:\Program Files\New Relic\newrelic-infra\custom-integrations\nri-perfmon\config.json`
- [ ] `C:\Program Files\New Relic\newrelic-infra\custom-integrations\nri-perfmon-definition.yml`
- [ ] `C:\Program Files\New Relic\newrelic-infra\integrations.d\nri-perfmon-config.yml`

**Comment by sschwartzman** [comment]
@KWLynch - any update or should I close this issue?

**Comment by sschwartzman** [comment]
Closing for now, will reopen if you can share the config files to review.
