### ISSUE TITLE
Error in the Infra Agent logs

### ISSUE THREAD

**Issue by stevescott34** [newrelic/nri-perfmon#30]
Seeing this error in the infra agent logs while the vri-perfmon is running

any guidance you can provide would be greatly appreciated.

time="2021-02-22T10:06:48-05:00" level=error msg="Integration command failed" error="exit status 3762504530" instance=nri-perfmon-metrics integration=com.newrelic.perfmon prefix=integration/nri-perfmon stderr="\nUnhandled Exception: Newtonsoft.Json.JsonSerializationException: Unexpected end when deserializing array. Path 'counterlist[0]', line 11, position 1.\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ThrowUnexpectedEndException(JsonReader reader, JsonContract contract, Object currentObject, String message)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at NewRelic.Program.Main(String[] args) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Program.cs:line 102\n" working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations"

**Comment by sschwartzman** [comment]
Did you build a custom counter file? This error indicates it had trouble parsing it:
```
Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Unexpected end when deserializing array. Path 'counterlist[0]', line 11, position 1.
```
If so, can you attach your config file?

**Comment by stevescott34** [comment]
Hi here is the config file which I assume is the default one. thanks for the quick response

[config.zip](https://github.com/newrelic/nri-perfmon/files/6031574/config.zip)

**Comment by sschwartzman** [comment]
Hmm, that is the default one, line 11 doesn't look any different from the others, so I'm not sure what's going on here. Let's run down a checklist:

- The file you just provided, did you copy it from the host where nri-perfmon is running?
- Did you install the latest version from here? https://github.com/newrelic/nri-perfmon/releases/latest
- When you installed it, did you unzip it on the host where you were installing?
- Did you customize anything at all in nri-perfmon?
- What version of Windows is this and what version of .NET Framework is installed on that host?

**Comment by stevescott34** [comment]
I re-installed both the new relic infra agent and the perfmon integration and all appears to be fine now. I can see the data in New Relic now.  I suspect it was something hanging around from a previous attempt to deploy.

Thanks again for the help and for the quick responses !

Let's consider this ticket closed

**Comment by sschwartzman** [comment]
No problem, glad it worked out!
