### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by stevescott34** [newrelic/nri-perfmon#31]
We are successfully pulling all of the default metrics into New Relic and seeing them populating there.

The question is related to the Webservice monitor and CurrentConnections metric. We can filter by APM Application Name and by the CurrentConnections but we receive only the total amount of connections and not broken down by the amount of each application individually. ( as we have 20+ applications on one server in IIS ) 

So the question is it possible to get the actual connection count broken out by application vs the server level connections ?

Any help you can provide is appreciated

Thank you

**Comment by icpenguins** [comment]
@stevescott34 hey, I appreciate the question! Unfortunately, I don't fully understand the context you are referring to with the above details. I believe what I am missing is the data you are collecting using the `nri-perfmon` integration. Could you share the configuration file for the performance counters? I just want to make sure I'm clear on that part.

What you are saying about the APM app name not being found in the performance counter metrics is likely true. What we would need to do is determine, from my above request, what details from IIS you are capturing and see if we can find a method to map a value from IIS (like AppPool name) to the APM app name.

**Comment by stevescott34** [comment]
thanks for the response , we successfully implemented the integration , we do have on last question and that is what is the correct process to remove the integration once installed. Just want to remove it from a test environment it is no longer needed in.

thanks for your help !

**Comment by icpenguins** [comment]
@stevescott34 removal should be pretty straightforward. In the configuration for the `infrastructure agent`. The is an install script located here that you could review and make sure that the given directories don't have the `nri-perfmon` integration on it anymore.

https://github.com/newrelic/nri-perfmon/blob/master/nri-perfmon/install/install-windows.ps1
