### ISSUE TITLE
Cannot Compile From Source/Release

### ISSUE THREAD

**Issue by Nateb1121** [newrelic/nri-perfmon#52]
In #50 code was introduces into the repo that causes it to no longer compile due to a missing semi-colon. 
![image](https://github.com/newrelic/nri-perfmon/assets/5375090/6d8f6cdb-e278-483f-8fac-c93cfc30b4bb)

In release 0.6.2 a zip of the source is included which has the same issue. 

I've attempted to compile this using 
* Microsoft Visual Studio Enterprise 2019 Version 16.11.32
* Microsoft Visual Studio Enterprise 2022 (64-bit) - Current Version 17.8.2

Are changes being introduced at build time that aren't being reflected in source control?

**Comment by Nateb1121** [comment]
@miransar, is there an explanation for how changes got introduces between source and build time? The concern here is that someone could introduce changes (as happened in this case) without those changes being reflected in the public source.

**Comment by miransar** [comment]
@Nateb1121 Thanks for bringing this to attention. It might have been a build time fix, I will see if it makes sense to bring in some checks on this repo.
