### ISSUE TITLE
Metrics not visible in New Relic

### ISSUE THREAD

**Issue by JohnLahr** [newrelic/nri-perfmon#8]
Using the latest release version on Server 2016 and .NET Framework 4.7.2, we're not seeing anything being shipped to New Relic. We've tried building from the master branch, updating the New Relic infrastructure agent, and tried using Windows Server 2012R2 instead of 2016, and even installing both manually and automatically via the PowerShell file, but nothing seems to work.

As far as I can tell, there is nothing glaringly obviously wrong being denoted by the logs. Where are we supposed to be seeing these new perfmon metrics? Am I just looking in the wrong place, maybe? I've been searching the New Relic infrastructure inventory page for the prefix `integration/nri-perfmon` from the default JSON configs, but don't see anything.

[newrelic-infra.log](https://github.com/newrelic/nri-perfmon/files/3687980/newrelic-infra.log)
[config.json](https://gist.githubusercontent.com/JohnLahr/c340a9980ffb518043a282a44a60de48/raw/1f153191facd7b29a2d877656379f96c0047cd13/config.json)
[nri-perfmon-definition.yml](https://gist.githubusercontent.com/JohnLahr/32931e54cd30b975c66f0e1820f97581/raw/3c3760b25218d95ba2338739dd189a8cbc379b54/nri-perfmon-definition.yml)
[nri-perfmon-config.yml](https://gist.githubusercontent.com/JohnLahr/f911176da81d80036a1d21b199827a4b/raw/f4991d26fdb16e9741cacabc947d31889798fb4f/nri-perfmon-config.yml)

**Comment by sschwartzman** [comment]
All of the data will appear as custom events in NRDB/Insights. The event type is governed by what's in your config.json - specifically the `category` field. If you're using the default config file, the event types are:
ASPNETApplications
NETCLRExceptions
NETCLRInterop
NETCLRJit
NETCLRLoading
NETCLRLocksAndThreads
NETCLRMemory
ASPNETStateService
ASPNET
WebService

Can you look in Insights for your account to see if those events appear while your agent is running?

**Comment by sschwartzman** [comment]
@JohnLahr I'm going to close this out unless it is still an issue after looking in Insights. If it still remains a problem after you've checked there, please let me know and we can reopen.
