### ISSUE TITLE
Windows Server 2019 and .NET requirements

### ISSUE THREAD

**Issue by jeremymaes** [newrelic/nri-perfmon#9]
Hey

I'm trying to run the integration on Windows Server 2019 and when I try to launch the integration after installing it I get a popup to install the .NET framework 3.5.

Now on the README it says '.NET Framework 3.5 or greater (including all 4.x installations)", but even though the server has .NET framework 4.7 installed it doesn't seem to work with that.

Is this a .NET version that has been tested, or do I need any specific extras for 4.7?

![2019-10-07 16_34_35-Clipboard](https://user-images.githubusercontent.com/56264393/66321109-60934400-e920-11e9-8fed-ac5c037f98c2.png)

Kind regards,
Jeremy

**Comment by sschwartzman** [comment]
One thing to check, is nri-perfmon.exe.config in the same directory as nri-perfmon.exe (once installed)? If so, can you edit to see if it lists both v.4.0 and v.2.0.xxxxxx? If v.4.0 is listed there, it should "just work" with a .NET Framework 4.x install.

**Comment by jeremymaes** [comment]
@sschwartzman And you've just fixed it. The README for the manual install doesn't say that the nri-perfmon.exe.config has to be put in the nri-perfmon dir aswell (or at least I didn't see it if it is). After putting it there it works. Thanks!

**Comment by sschwartzman** [comment]
Ahh, so you did a manual install! I'll add that to the README.
